include: package:very_good_analysis/analysis_options.2.4.0.yaml
analyzer:
  # Excluding generated files
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
linter:
  rules:
    public_member_api_docs: false
    library_private_types_in_public_api: false
    implementation_imports: false